server:
  port: 8081
  servlet:
    context-path: /mezapay

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meza
    username: meza
    password: meza@BNK#2023
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
